name: Update Folk 

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 12 * * 0-6'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Kin'
          git config --global user.email 'kenneth.quan1@nhs.net'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/opensafely/ADHD-Pre-and-Post-Covid.git
          git fetch upstream

          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          git checkout -b tmp origin/main
          git merge --no-edit upstream/main

          git checkout main
          git merge --no-edit tmp
          git push